/**
 * Research Ledger design: chronological research entries preserve uncertainty in an editorial ledger,
 * with explicit evidence stamps rather than retrospective cleanup.
 */
import { ArrowUpRight, CalendarDays, FileWarning, GitCommitHorizontal, Lightbulb } from "lucide-react";
import { StatusStamp } from "@/components/StatusStamp";

const entries = [
  { date: "21 AUG 2026", title: "Documentation mirror deployed on Render with verified SPA routing", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A Render Static Site now serves the public documentation mirror at `https://federated-aggregator-docs.onrender.com`. Render built the public `main` branch at commit `a198ceb` using `pnpm install --frozen-lockfile && pnpm vercel-build` and published `./dist/public`. Both the root route and the direct `/research-log` route were opened successfully after a `/*` to `/index.html` rewrite was saved. The existing managed documentation deployment remains online. The reproducible configuration is committed locally, but its GitHub push is blocked because the sandbox GitHub credential is invalid; until that credential is restored, the remote `main` branch has not received this deployment-configuration commit." },
  { date: "21 AUG 2026", title: "Phase 14 staged milestone: reproducible infrastructure validation artifacts", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now includes a disposable Redis primary/two-replica/three-Sentinel topology, a Sentinel runbook for controlled failover observation, and a Collector configuration-validation command artifact. The runbook requires evidence to be stored as a bounded reference/digest and explicitly flags whether the current single-URL limiter is Sentinel-aware rather than assuming it is. Static whitespace, format, lint, type, and test checks passed. Docker is unavailable in this sandbox, so the topology, failover, Collector validation, health, backend delivery, and alert receiver were not executed. These artifacts are a reproducible plan, not runtime assurance." },
  { date: "21 AUG 2026", title: "Phase 13 staged milestone: deployment evidence now has an expiry policy", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Every new deployment attestation now carries a `reviewedAt` timestamp and a fixed 90-day `expiresAt`; the additive migration backfills existing records from their prior review time. The protected Core summary and portal-safe type include expiry only, never the underlying provider configuration, endpoint, credential, evidence reference, or pager destination. Expiry means a review is no longer current enough for this product policy; it does not diagnose a deployment fault or prove configuration drift. Full CI passed 43 TypeScript tests plus 4 Python tests and PostgreSQL migration/integration execution; the portal build passed. A real multi-instance Redis outage/failover exercise and deployed Collector/backend/alert-receiver validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 12 staged milestone: provider verification records uncertainty without retry", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "An active platform administrator can now resolve a `recovery_pending_verification` disposal with a bounded provider observation: `object_absent`, `object_present`, or `provider_unavailable`. Each resolution appends immutable evidence containing an opaque external reference, digest, verified identity, and correlation ID. It never calls storage, replays the old deletion, reuses approval, or claims sanitization, backup/replica erasure, or compliance completion. The portal recognizes the redacted lifecycle state only; it receives no reference, digest, raw provider response, storage locator, version, or browser resolution control. Full CI passed 43 TypeScript tests plus 4 Python tests and the new PostgreSQL migration/integration suite passed; the portal production build passed." },
  { date: "21 AUG 2026", title: "Phase 11 staged milestone: deployment attestations preserve evidence boundaries", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now records reviewed deployment-attestation references for storage lifecycle, telemetry/alerting, and shared rate-limiter scopes. Only a platform administrator can record an attestation; federation-owner governance readers receive a redacted summary containing scope, assurance label, digest, and review time. Raw provider configuration, credentials, object locators, model/artifact bytes, and patient data are excluded. Audit/outbox evidence stores the safe digest only. The administrator portal renders a protected deployment-evidence count and has no browser recording control. Full CI passed 42 TypeScript tests plus 4 Python tests, including PostgreSQL migration/integration execution; the portal production build passed. Attestation expiry, provider-backed recovery resolution, and live Redis/Collector topology tests remain deferred." },
  { date: "21 AUG 2026", title: "Phase 10 staged milestone: stale disposal recovery records uncertainty", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A disposal stuck in `executing` for more than fifteen minutes can now be moved only by an active platform administrator, with a non-empty reason, into `recovery_pending_verification`. This appends immutable recovery, audit, and outbox evidence and deliberately makes no storage call or deletion claim. The Core rejects recovery of a fresh, non-executing, or unavailable disposal; it cannot silently reuse the prior execution path. The portal recognizes the redacted recovery state but exposes no browser recovery/execution control. Full CI passed 40 TypeScript tests plus 4 Python tests and the PostgreSQL migration passed. Provider-backed storage verification, Object Lock/lifecycle attestations, Redis failure-mode testing, and Collector runtime validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 9 staged milestone: shared controls and safe disposal lifecycle view", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now selects a Redis-backed atomic fixed-window limiter for privileged commands whenever `REDIS_URL` is configured; a no-Redis process-local limiter remains only a development fallback. A new federation-owner-authorized disposal summary exposes lifecycle state, approval count, correlation ID, timestamp, and bounded outcome category—but never object keys or versions, reasons, descriptors, raw audit/outbox records, artifacts, or model bytes. The administrator portal renders that redacted view and requires an explicit reason to record an owner approval; browser execution remains unavailable. Collector self-metrics and portable alert-rule templates were added. Full Core CI passed 39 TypeScript tests plus 4 Python tests and the portal build passed. Docker/Collector, Redis-failure, storage policy, and alert-receiver runtime validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 8 core delivered: bounded telemetry, operational throttling, and dual-authorized disposal", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core can now emit best-effort, allowlisted OpenTelemetry metrics to a configured local OTLP Collector while preserving a no-op default and never letting telemetry failure affect governance state. Privileged retry, dead-letter, disposal-request, approval, and execution commands are rate-limited per verified local principal and operation class before mutation, returning explicit 429/Retry-After information when blocked. A reviewed candidate can enter a storage-disposal request only after a `dispose_authorized` review; the requester cannot approve it, two distinct active federation-owner governors must approve, and an active platform administrator executes a frozen version-aware storage locator. Request, approval, execution result, correlation, and bounded failure category are immutable; candidate/release/audit lineage is retained. The full CI gate passed 39 TypeScript tests plus 4 Python tests. The portal remains review-only because no safe disposal-summary read model yet exists." },
  { date: "21 AUG 2026", title: "Phase 7 delivered: separate human administrator portal and safe governance read models", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A private `paradox-tech-bd/federated-aggregator-admin-portal` repository now contains a separate React/Vite human control surface for delivery operations, candidate/release lineage, and review-only retention work. The Core exposes only federation-scoped, role-authorized candidate/release summaries; it never returns artifact/model bytes, patient data, raw event payloads, approval-policy internals, or release envelopes through the portal. Retry/dead-letter controls require explicit reasoned confirmation and preserve correlation/audit evidence. The portal uses visibly labeled preview fixtures until a Core URL, explicit federation ID, and future OIDC session adapter are configured. The Core CI passed 36 TypeScript tests plus 4 Python tests, including protected PostgreSQL read-model integration coverage; the portal production build passed." },
  { date: "21 AUG 2026", title: "Phase 6 core delivered: dependency readiness and controlled outbox operations", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The control plane now distinguishes process liveness from dependency-aware readiness across PostgreSQL, Redis, and object storage. Transactional-outbox events carry explicit pending, published, or dead-lettered delivery state, safe failure metadata, and immutable operator-action evidence. Only an active platform administrator can inspect delivery summaries, request a retry, dead-letter an unpublished event, or review retention-due candidates; event payloads stay immutable and are not returned by the operations view. The publisher excludes dead-lettered events from claim, acknowledgement, and failure paths. Full CI passed 36 TypeScript tests plus 4 Python tests." },
  { date: "21 AUG 2026", title: "Phase 5 core delivered: governed candidate, evidence, release, rollback, and retention lifecycle", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "An accepted aggregation result is now only the start of a governed candidate lifecycle, not an automatic model release. The core freezes the candidate descriptor, accepted worker-result digest, protocol, release policy, and retention date; it accepts descriptor-only evaluation evidence, enforces that a creator cannot approve their own candidate, counts distinct owner-organization approvals, and publishes an immutable release envelope bound to candidate, evidence, and approval digests. Controlled rollback either selects a compatible published fallback or suspends the release with a reason. Retention decisions are recorded for review only; no object is automatically deleted. The full CI gate passed 32 TypeScript tests plus 4 Python tests." },
  { date: "21 AUG 2026", title: "Phase 4 core delivered: verified dispatch, deterministic aggregation, and safe worker reconciliation", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A sealed round can now freeze its exact verified, round-bound model-update descriptors into a versioned Node–Python command with a canonical digest. A lease-aware transactional-outbox publisher dispatches only committed jobs through a retry-safe BullMQ job identity; the isolated Python worker performs deterministic weighted FedAvg/FedProx-compatible server aggregation and returns a descriptor-only result. A separate active ML-worker identity must match the federation-owner organization, and its result must match the dispatched command, immutable input evidence, and digest before candidate-ready state is recorded. Stale, malformed, mismatched, or duplicate callbacks cannot mutate candidate state. The full CI gate passed 31 TypeScript tests plus 4 Python tests, including PostgreSQL migration and reconciliation coverage." },
  { date: "21 AUG 2026", title: "Phase 3 core delivered: descriptor-only artifact intake and quarantine", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private core now issues a short-lived, checksum-constrained S3-compatible upload intent for a generated staging key while keeping artifact bytes outside the API and PostgreSQL. Artifact, upload-intent, and append-only verification records preserve only descriptors, manifests, integrity facts, audit events, and outbox evidence. Local membership and federation participation govern creation; metadata mismatch, expiry, or an unavailable object is quarantined. The PostgreSQL migration ran successfully and the Phase 3 suite passes 24 tests." },
  { date: "21 AUG 2026", title: "Phase 2 core delivered: persistence, local authorization, and controlled API edge", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private product-core repository now has a reviewed Drizzle/PostgreSQL migration covering governance, participation, protocol/round history, audit, idempotency, and transactional outbox records. A remote-JWKS OIDC adapter validates issuer/audience/signature; a verified human still requires an active local principal and membership scope. NestJS provides liveness, dependency-aware readiness, and an authorization-filtered federation read. The migration executed on PostgreSQL 16 and the Phase 2 evidence suite passes 17 tests, including atomic state/audit/outbox commit and rollback." },
  { date: "21 AUG 2026", title: "Product-core repository established: tested local governance baseline", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A private `paradox-tech-bd/federated-aggregator-core` repository now holds the Phase 0–1 foundation: strict TypeScript/Python workspaces, contracts and ports, local dependency topology, CI, and deterministic domain tests for scoped memberships, non-human workload separation, protocol immutability, and round transitions. The baseline retains the approved OIDC/Clerk-ready human boundary, local authorization authority, workload credential separation, and MetaMask deferral." },
  { date: "21 AUG 2026", title: "Handoff plan fixed: local authority required; Clerk supported; MetaMask deferred", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The first core release requires local PostgreSQL records for users, organizations, memberships, workloads, federation scope, and evidence-backed authorization. Human sign-in remains provider-owned through OIDC; Clerk is an acceptable managed option for a later portal, but its session/organization context cannot replace backend policy. Hospital and worker identities remain separate short-lived credentials. MetaMask/SIWE is a future optional human authentication factor only, with no v1 schema or runtime path." },
  { date: "21 AUG 2026", title: "Engineering standard defined: modular monorepo, clean boundaries, and layered proof", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The future core repository is specified as a pnpm/TypeScript workspace plus independent Python packages: NestJS API, Node dispatch worker, and private ML worker. Domain capabilities own policy; framework/storage/queue/identity concerns are adapters; Node–Python communication is versioned schema plus golden fixtures; clean-room behavior is preserved as verified reference tests rather than imported product coupling." },
  { date: "21 AUG 2026", title: "Full core wiring specified: authority, artifacts, jobs, workers, and recovery", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The architecture now makes every integration boundary explicit: OIDC/workload identities, NestJS command authority, PostgreSQL state/audit/outbox, constrained object storage, Redis/BullMQ dispatch, a private Python/PyTorch worker, full callback reconciliation, network isolation, observability, and governed rollback. The core is intentionally a control plane, not a hospital-data repository." },
  { date: "21 AUG 2026", title: "Workflow boundary formalized: round-to-release evidence chain", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The core workflow now separates protocol activation, eligible-node selection, local training, submission quarantine, frozen-input aggregation, evaluation evidence, accountable release approval, and rollback. It records FedProx μ as client-side provenance and excludes raw hospital data from the core." },
  { date: "20 AUG 2026", title: "Technical boundary accepted for review: Node.js control, Python ML", status: "PROVISIONAL" as const, icon: GitCommitHorizontal, body: "The next architecture gate proposes a NestJS modular control plane, PostgreSQL domain state, artifact storage, and a separate PyTorch worker contract. Earlier prototypes are explicitly classified as reuse, rewrite, or defer." },
  { date: "20 AUG 2026", title: "Requirements gate opened before core architecture", status: "PROVISIONAL" as const, icon: FileWarning, body: "The product now has a written non-technical analysis covering stakeholder outcomes, business value, governance, research gaps, risks, and explicit assumptions to accept before backend design." },
  { date: "20 AUG 2026", title: "One product first: aggregation core and admin portal", status: "VALIDATED" as const, icon: Lightbulb, body: "Hospital nodes, hospital portals, and external coordination layers are separated from the first product. The immediate concern is a trustworthy model-release control plane." },
  { date: "20 AUG 2026", title: "Terminology correction: FedProx does not change the server’s basic role", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The proximal penalty is applied during local client optimization. The aggregator validates and combines declared client updates, records μ, and publishes the next compatible global model." },
  { date: "19 AUG 2026", title: "Legacy low-specificity / high-sensitivity result is retained as a diagnostic", status: "PROVISIONAL" as const, icon: FileWarning, body: "The pattern is not a thesis claim. It remains a debugging signal pending a corrected aggregation implementation, grouped data split, reproducible configuration, and independent metric recalculation." },
];

export default function ResearchLog() {
  return (
    <div className="doc-page research-page">
      <header className="doc-topbar"><p>12 / RESEARCH LOG</p><span className="topbar-meta"><CalendarDays size={15} />GMT+6 chronology</span></header>
      <section className="page-title"><p className="folio">12.0 / DECISIONS OVER TIME</p><h1>Keep the failed runs.<br /><i>They are evidence too.</i></h1><p>Every consequential change records its context, evidence, decision, consequence, status, and next action. The log is chronological by design.</p></section>
      <section className="log-ledger">{entries.map((entry, index) => { const Icon = entry.icon; return <article className="log-entry" key={entry.title}><div className="log-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="log-date">{entry.date}</div><div className="log-content"><div className="log-title-row"><h2>{entry.title}</h2><StatusStamp status={entry.status} /></div><p>{entry.body}</p><a href="#open-decisions">Evidence and decision record <ArrowUpRight size={15} /></a></div><Icon className="log-icon" size={21} /></article>; })}</section>
      <section id="open-decisions" className="open-questions"><div><span>OPEN DECISION / 008</span><h2>Which normalization policy belongs in the production vision model?</h2></div><p>Before the actual vision architecture enters a federated round, document whether BatchNorm buffers are aggregated, retained locally, frozen, or replaced. The answer must be tested on that architecture, not inferred from the earlier MLP simulation.</p><StatusStamp status="BLOCKED" /></section>
    </div>
  );
}
