/**
 * Research Ledger design: chronological research entries preserve uncertainty in an editorial ledger,
 * with explicit evidence stamps rather than retrospective cleanup.
 */
import { ArrowUpRight, CalendarDays, Database, FileWarning, GitCommitHorizontal, Lightbulb, ShieldCheck, Workflow } from "lucide-react";
import { StatusStamp } from "@/components/StatusStamp";

const entries = [
  { date: "22 AUG 2026", title: "Command-route prerequisite fixed: Core must own the canonical node command", status: "PROVISIONAL" as const, icon: Workflow, body: "Review of the implemented Core state found that its protocol-version record stores algorithm, architecture, and a configuration digest, but not every field required by the Agent’s already-tested `hospital-node-command/v1` validator. A digest cannot safely reconstruct proximal coefficient, local epochs, model/preprocessing digests, or base-model checksum/size. Before any lease controller is added, the Core will therefore store one canonical descriptor-only command payload alongside its computed digest at assignment creation. The payload has only immutable identifiers, expiry, safe algorithm/training parameters, digests, and size/checksum; it excludes provider URLs, object keys, credentials, bytes, paths, free text, and patient fields. This is a design-and-schema prerequisite, not a route, human command editor, node call, Keycloak client, capability, or deployment." },
  { date: "22 AUG 2026", title: "Core persists one safe, idempotent hospital-node lease per assignment", status: "VALIDATED" as const, icon: Database, body: "Core commit `263e596` adds the PostgreSQL hospital-node assignment repository and a migrated-database integration test. The adapter returns context only when assignment, workload, and participant records agree; returns the existing `(assignment_id, idempotency_key)` lease on recovery; refuses a second active lease; advances only an exact assigned workload/digest to `leased`; and appends one scalar-only `lease_issued` event. Migration `0010` is now registered in the migration journal, and a partial database unique index permits only one active lease for each assignment. Full local CI passed with 49 TypeScript and nine Python tests; Core Quality Gates passed in 1 minute 37 seconds and the protected Azure deployment completed in 2 minutes 49 seconds. Public liveness and strict readiness returned HTTP 200. No Core controller/route, Keycloak client, capability, command body, artifact update, submission, real node, hospital data, or worker-gate change exists yet." },
  { date: "22 AUG 2026", title: "Core separates the hospital-node OIDC audience from the ML worker", status: "VALIDATED" as const, icon: ShieldCheck, body: "Core commit `92c6c53` adds a dedicated `HospitalNodeAuthGuard` provider that verifies only the `fedagg-hospital-node` audience, requires an active local workload principal, and rejects every workload kind other than `hospital_node`. Its two deterministic tests prove an active hospital-node identity attaches to the workload request while an active `ml_worker` is denied. The existing internal worker-callback guard remains on its different `fedagg-worker-callback` audience and is unchanged; no controller uses the new guard yet. Full local CI passed with 48 TypeScript and nine Python tests, including migration/integration execution; Core Quality Gates passed in 1 minute 42 seconds and the protected Azure deployment completed successfully. Public liveness and strict readiness both returned HTTP 200. No Keycloak node client, API route, token, capability, Node request, hospital data, or worker-gate change was added; the worker remains explicitly disabled by default." },
  { date: "22 AUG 2026", title: "Core deploys additive hospital-node assignment, lease, and safe-event schema", status: "VALIDATED" as const, icon: Database, body: "Core commit `31e7588` adds the reviewed `0010_hospital_node_assignments.sql` migration and matching schema declarations for Core-owned assignment, lease, and append-only safe-event records. Foreign keys bind assignments to existing participant/round/workload records; unique constraints prevent duplicate round-workload assignments and duplicate assignment/idempotency leases. The only stored evidence is digest, deadline/state, correlation, safe event type, and scalar-safe details—never a data field, local path, token, capability, URL, object key, artifact byte, or remote response. Full local CI again passed with 46 TypeScript and nine Python tests, including migration/integration execution; Core Quality Gates passed in 1 minute 36 seconds and the protected Azure deployment completed successfully. Public liveness and strict readiness both returned HTTP 200. No persistence adapter, API controller, audience/guard, Keycloak client, capability, submission route, real node, hospital data, or worker-gate change exists yet." },
  { date: "22 AUG 2026", title: "Core adds the first isolated hospital-node lease policy slice", status: "VALIDATED" as const, icon: ShieldCheck, body: "Core commit `79bdcee` begins the documented hospital-node implementation in the narrowest possible layer: shared assignment/lease vocabulary, a domain transition matrix, and an application service that permits a lease only for an active `hospital_node` workload with an active participant, open round, assigned state, and future deadline. It includes three deterministic tests that reject both an `ml_worker` and an expired assignment before any repository write. There is still no Core migration, database adapter, Nest controller, OIDC audience/guard, Keycloak client, artifact capability, submission route, Node-to-Core request, or Azure node. The local full suite passed with 46 TypeScript and nine Python tests; Core Quality Gates passed in 1 minute 32 seconds and the protected Azure deployment completed successfully. Public liveness and strict readiness both returned HTTP 200. The default-disabled aggregation worker was not enabled or changed." },
  { date: "22 AUG 2026", title: "Core hospital-node workload contract is designed before integration", status: "PROVISIONAL" as const, icon: Workflow, body: "A new Core contract design now defines the required path for Hospital Node integration without shortcutting through an existing human or ML-worker endpoint. It requires a dedicated `fedagg-hospital-node` audience and guard; active `hospital_node` workload, organization, participant, round, deadline, and lease checks; additive assignment/lease/submission/event tables; descriptor-only artifact intent and verified submission; allowlisted incompatibility reporting; safe audit/outbox evidence; and a tightly bounded Azure synthetic proof. The design is explicit that the existing `hospital_node` workload kind and `model_update_archive` category are not by themselves a usable node API. No Core route, migration, Keycloak client, storage capability, human-route reuse, Azure node, hospital data path, or deployment has been added. The next implementation work begins in Core domain/schema/authorization tests, then contract-controlled HTTP routes." },
  { date: "22 AUG 2026", title: "Hospital Node Agent adds an opt-in localhost-only synthetic status read", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Commit `e11d661` gives the Hospital Node Agent its first directly testable service boundary: an opt-in `GET /status` listener whose normal host is loopback only. A fixed redacted payload says only that the service is synthetic, Core integration is unconfigured, and local data is not exposed. The status process stays disabled unless explicitly enabled; binding to a private Compose network requires a distinct test-mode flag, and the supplied Compose profile maps its port only to the Docker host loopback. Hospital Node Quality Gates #5 passed remotely in 20 seconds, exercising the loopback response and the private-network refusal. Docker is not available in this sandbox, so the image and Compose profile are static test artifacts, not container runtime evidence. There is still no Core connectivity, public port, deployment, raw data path, model byte endpoint, hospital asset, or clinical feature." },
  { date: "22 AUG 2026", title: "Hospital Node adapters enforce scoped synthetic transfer boundaries", status: "VALIDATED" as const, icon: ShieldCheck, body: "The Hospital Node Agent has completed its next in-memory adapter slice across commits `deee8a6` and `1dcff80`. A scoped object capability now requires the exact assignment, operation, and unexpired lease; synthetic object storage rejects a checksum mismatch before returning only a checksum/size descriptor. The test token source is audience-bound, expiry-bound, and process-memory-only. A classifier distinguishes accepted, retryable temporary/timeout, and terminal remote outcomes without taking an automatic retry action. Hospital Node Quality Gates #3 and #4 both passed remotely; the final gate completed in 30 seconds with ten TypeScript tests and four Python FedAvg/FedProx tests. This is contract-bound synthetic evidence only: no Azure call, Core workload endpoint, human/ML-worker credential reuse, signed URL, object locator, persistent token, external storage, hospital data, or deployment has been introduced." },
  { date: "22 AUG 2026", title: "Hospital Node Agent receives restart-safe local control state", status: "VALIDATED" as const, icon: Database, body: "Commit `2468f4b` adds a deliberately narrow local control-state increment to the private Hospital Node Agent. The synthetic node now uses Node.js 22 built-in SQLite for a composite `(assignment_id, idempotency_key)` run record plus append-only event labels. Its application layer returns a recovered terminal run before it can train or submit again; a file-backed restart test proves that an already accepted run issues no duplicate fake-Core submission. The new in-process Core submission/assignment fakes remain contract-test adapters rather than a network client. Hospital Node Quality Gates #2 passed remotely in 18 seconds, including five TypeScript tests and the four Python FedAvg/FedProx tests. The node still has no local status service, artifact capability, workload token client, retry classifier, object transfer, Core hospital-node routes, real hospital data, or deployment; Node’s experimental SQLite runtime support and the redacted status projection remain documented decisions for subsequent slices." },
  { date: "22 AUG 2026", title: "Next system selected and documented: separate Hospital Node Agent", status: "VALIDATED" as const, icon: Workflow, body: "The completed Core ledger now hands off to a separate hospital-local training workload rather than expanding the Core into a patient or hospital-information system. The new private `hstu-research/federated-aggregator-hospital-node` repository began with a documentation-first dossier covering product/non-technical and technical requirements, local-only schema, normal and exception workflows, deployment architecture, engineering standards, proposed workload API, and an AI implementation handoff. Commit `cfcf1dc` passed Hospital Node Quality Gates #1: strict formatting/type checks, four TypeScript synthetic command/execution tests, and four Python FedAvg/FedProx primitive tests. The baseline accepts only generated values; it does not implement real Core workload routes, hospital data, patient upload, blockchain/IPFS, a browser portal, or clinical inference. The next slice is local SQLite restart safety and fake Core/storage ports before separate Core workload-contract work begins." },
  { date: "22 AUG 2026", title: "One bounded worker callback accepted; Redis remains direct after non-promotion evidence", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private Azure test path has now completed one deliberately bounded, synthetic FedProx aggregation proof. Commits `e92b527`, `bba2dab`, and `98e3989` passed Core Quality Gates runs 32–34 and protected Azure deployments 17–19. The profile-gated runner created a synthetic federation, sealed round, two tiny worker-local parameter archives, verified descriptors, and one queue job; its first enablement exposed two configuration gaps—missing private callback URL and a non-root secret-read permission—which were repaired without widening public access or exposing the client secret. The existing dispatched synthetic job then completed through the real outbox, BullMQ worker, Keycloak client-credentials token, and authenticated descriptor-only callback. PostgreSQL recorded `succeeded|candidate_ready|enqueued|accepted`; the worker gate was immediately restored to its default disabled state, and Azure internal/public liveness and readiness returned HTTP 200. The separate primary/two-replica/three-Sentinel harness observed primary loss and a final `subjectively_down` state but no promotion during its bounded window; the topology was torn down, and the Core still uses a direct Redis URL rather than claiming Sentinel-aware failover." },
  { date: "22 AUG 2026", title: "Federated research portfolio moved to hstu-research", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Repository ownership is now centralized under `hstu-research`: the private Core, public documentation ledger, private administrator portal, and private thesis research rebuild were transferred with their existing GitHub history and default branches. Local Core, portal, thesis, and the documentation workspace’s named GitHub remote now target the new organization; current source references and runbooks no longer name the former owner. Core Quality Gates run 31 and protected Azure deployment run 16 both completed successfully from `hstu-research/federated-aggregator-core`, confirming that the repository-local SSH release path remained intact. Render’s Core API source now identifies `hstu-research/federated-aggregator-core`; the documentation static site rebuilt successfully from `hstu-research/federated-aggregator-docs` commit `3a8e65b`. Azure remains the authoritative environment, while Render remains a backup path. Historical ledger dates are retained, but active instructions and deployment links use the new organization." },
  { date: "22 AUG 2026", title: "Private Azure workload identity verified; aggregation remains explicitly disabled", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Azure remains the authoritative test control-plane environment. Core commit `d35bebc` completed Core Quality Gates run 30 and protected Azure deployment run 15 after the release path self-provisioned its protected test client-secret file, synchronized its activation helper, and corrected worker/bootstrap image packaging and a PostgreSQL bootstrap query type conflict. The private Keycloak service is healthy; its one-shot bootstrap acquired a client-credentials token and recorded an active local `ml_worker` mapping without exposing the subject, token, secret, raw model bytes, descriptors, or patient data. The aggregation worker starts only after that bootstrap succeeds, then logs its disabled state because `AGGREGATION_WORKER_ENABLED=false` remains the default. Public Azure liveness and readiness both returned HTTP 200. A bounded synthetic queue-and-callback exercise is the next required proof before any explicit worker enablement." },
  { date: "22 AUG 2026", title: "Azure authority retained; Render remains liveness-only and Redis stays direct", status: "VALIDATED" as const, icon: Lightbulb, body: "The operational hierarchy is now explicit: Azure owns the Core execution and release-control path, while the Render free API and Cloudflare-managed backup components remain non-primary continuity paths. Render liveness is publicly available, but strict readiness remains HTTP 503 because the object-storage dependency is not accepted as ready; it must not be used for workload dispatch, authority, or release state. The Azure Redis Sentinel revalidation also remains a negative result: Sentinels detected primary loss but recurring tilt and no-good-slave outcomes prevented a repeatable promotion. The test Core therefore continues to use a direct Redis URL until an isolated resilience pass produces stable failover evidence." },
  { date: "21 AUG 2026", title: "GitHub CI/CD validates and deploys the public Core test endpoint", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now has a protected `azure-test` GitHub Actions environment with a dedicated revocable SSH deployment key and verified host-key pin. On every `main` push, the workflow runs the full `pnpm run ci` gate, packages committed source, deploys it over SSH, and invokes the VPS atomic release runner. Commit `25c7073` completed both Core Quality Gates and the HTTPS test deployment successfully. The active Azure release is `25c70733229299a0b56ccf59c40ea7d19c26073f`; public liveness returned `{status: ok, component: api}`. Caddy alone is public; API dependencies, database, Redis, MinIO, dispatch, and telemetry remain private. This proves a test release path only, not Python-worker, OIDC, real storage, Sentinel, hospital, or clinical production readiness." },
  { date: "21 AUG 2026", title: "Public HTTPS Core test endpoint activated with private dependencies", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Following the Azure resize to two vCPUs and roughly 3.8 GiB RAM, a test-only Core stack was activated. Caddy is the sole public service and obtained an ACME certificate for `https://nirog.koreacentral.cloudapp.azure.com`; the API, PostgreSQL, Redis, MinIO, telemetry collector, and dispatch publisher stay on the private Docker network. Internal liveness and readiness checks passed. The release automation now performs CI before SSH archive deployment and rolls the `current` release symlink back on failed readiness, but it cannot auto-run until the commits are pushed and the repository deployment environment receives a dedicated SSH key, host, user, and host-key values. This is an integration test endpoint with synthetic local storage/database credentials and placeholder OIDC—not a hospital or production service." },
  { date: "21 AUG 2026", title: "Core receives a private deployment definition and durable dispatch entry point", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now has a separately supervised, signal-safe dispatch publisher entry point and a private-by-default container definition for PostgreSQL, Redis, internal telemetry, migrations, the Node API, and dispatch worker. The compose definition binds no host ports and expects a reverse proxy to be the only future public HTTPS surface. Full CI still passes with 43 TypeScript and 4 Python tests, and the Node runtime image built successfully on Azure without any real secrets or Core containers starting. It is deliberately not a complete production stack: the selected 891 MiB VPS is below the capacity gate; real protected secrets, Azure NSG/DNS/TLS, owner recovery access, and a Python aggregation-worker runtime with queue consumer, workload identity, storage adapters, and callback path remain required before any Core deployment." },
  { date: "21 AUG 2026", title: "Azure runtime validation corrected Sentinel startup but did not prove failover", status: "PROVISIONAL" as const, icon: FileWarning, body: "A disposable Azure Docker run accepted the committed Collector configuration-validation command. The Redis Sentinel harness initially exposed a Docker-DNS startup race; it was corrected with a mounted startup script that waits for name resolution and monitors the resolved private test address. The corrected primary/two-replica/three-Sentinel topology started and reported its initial master without publishing host ports. During a controlled primary stop, Sentinel marked the primary down but repeatedly entered tilt on the 891 MiB runner and did not elect a replacement before teardown. This is incomplete failover evidence, not proof of Sentinel-aware Core behavior, Redis high availability, or production readiness. The current Core limiter still accepts one Redis URL." },
  { date: "21 AUG 2026", title: "Azure VPS hardened and Core source staged; capacity gate remains", status: "PROVISIONAL" as const, icon: Lightbulb, body: "The selected Ubuntu VPS now has verified key-based operator access, an active default-deny host firewall with rate-limited SSH only, Fail2ban, unattended updates, Docker/Compose, bounded container log rotation, and 2 GiB swap. Core commit `630722b` is staged without sandbox credentials or Git history. The server currently has roughly 891 MiB RAM, which is not accepted for the full Core topology. No Core API, PostgreSQL, Redis/Sentinel, worker, telemetry collector, portal, clinical data path, or public HTTPS endpoint has been deployed; Azure NSG restriction, recoverable key-only owner access, appropriate capacity, production secrets, and runtime entry points remain gates." },
  { date: "21 AUG 2026", title: "Azure VPS hosting boundary prepared for the Core deployment", status: "PROVISIONAL" as const, icon: Lightbulb, body: "The next deployment phase now separates the public reverse-proxy surface from private Core dependencies: Core API, PostgreSQL, Redis/Sentinel, BullMQ, Python worker, and OpenTelemetry remain private; only HTTPS is public, with TCP 80 retained only when HTTP-01 certificate issuance is used. SSH is restricted to Azure Bastion, VPN, or a temporary approved CIDR. The Render documentation mirror stays separate. This is a staging/production-preparation topology, not a claim that the Core is deployed or a permission to co-locate hospital systems, patient data, clinical images, or arbitrary future applications on one public host." },
  { date: "21 AUG 2026", title: "Documentation mirror deployed on Render with verified SPA routing", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A Render Static Site now serves the public documentation mirror at `https://federated-aggregator-docs.onrender.com`. Render built the public `main` branch at commit `a198ceb` using `pnpm install --frozen-lockfile && pnpm vercel-build` and published `./dist/public`. Both the root route and the direct `/research-log` route were opened successfully after a `/*` to `/index.html` rewrite was saved. The existing managed documentation deployment remains online. The reproducible configuration is committed locally, but its GitHub push is blocked because the sandbox GitHub credential is invalid; until that credential is restored, the remote `main` branch has not received this deployment-configuration commit." },
  { date: "21 AUG 2026", title: "Phase 14 staged milestone: reproducible infrastructure validation artifacts", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now includes a disposable Redis primary/two-replica/three-Sentinel topology, a Sentinel runbook for controlled failover observation, and a Collector configuration-validation command artifact. The runbook requires evidence to be stored as a bounded reference/digest and explicitly flags whether the current single-URL limiter is Sentinel-aware rather than assuming it is. Static whitespace, format, lint, type, and test checks passed. Docker is unavailable in this sandbox, so the topology, failover, Collector validation, health, backend delivery, and alert receiver were not executed. These artifacts are a reproducible plan, not runtime assurance." },
  { date: "21 AUG 2026", title: "Phase 13 staged milestone: deployment evidence now has an expiry policy", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "Every new deployment attestation now carries a `reviewedAt` timestamp and a fixed 90-day `expiresAt`; the additive migration backfills existing records from their prior review time. The protected Core summary and portal-safe type include expiry only, never the underlying provider configuration, endpoint, credential, evidence reference, or pager destination. Expiry means a review is no longer current enough for this product policy; it does not diagnose a deployment fault or prove configuration drift. Full CI passed 43 TypeScript tests plus 4 Python tests and PostgreSQL migration/integration execution; the portal build passed. A real multi-instance Redis outage/failover exercise and deployed Collector/backend/alert-receiver validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 12 staged milestone: provider verification records uncertainty without retry", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "An active platform administrator can now resolve a `recovery_pending_verification` disposal with a bounded provider observation: `object_absent`, `object_present`, or `provider_unavailable`. Each resolution appends immutable evidence containing an opaque external reference, digest, verified identity, and correlation ID. It never calls storage, replays the old deletion, reuses approval, or claims sanitization, backup/replica erasure, or compliance completion. The portal recognizes the redacted lifecycle state only; it receives no reference, digest, raw provider response, storage locator, version, or browser resolution control. Full CI passed 43 TypeScript tests plus 4 Python tests and the new PostgreSQL migration/integration suite passed; the portal production build passed." },
  { date: "21 AUG 2026", title: "Phase 11 staged milestone: deployment attestations preserve evidence boundaries", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now records reviewed deployment-attestation references for storage lifecycle, telemetry/alerting, and shared rate-limiter scopes. Only a platform administrator can record an attestation; federation-owner governance readers receive a redacted summary containing scope, assurance label, digest, and review time. Raw provider configuration, credentials, object locators, model/artifact bytes, and patient data are excluded. Audit/outbox evidence stores the safe digest only. The administrator portal renders a protected deployment-evidence count and has no browser recording control. Full CI passed 42 TypeScript tests plus 4 Python tests, including PostgreSQL migration/integration execution; the portal production build passed. Attestation expiry, provider-backed recovery resolution, and live Redis/Collector topology tests remain deferred." },
  { date: "21 AUG 2026", title: "Phase 10 staged milestone: stale disposal recovery records uncertainty", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A disposal stuck in `executing` for more than fifteen minutes can now be moved only by an active platform administrator, with a non-empty reason, into `recovery_pending_verification`. This appends immutable recovery, audit, and outbox evidence and deliberately makes no storage call or deletion claim. The Core rejects recovery of a fresh, non-executing, or unavailable disposal; it cannot silently reuse the prior execution path. The portal recognizes the redacted recovery state but exposes no browser recovery/execution control. Full CI passed 40 TypeScript tests plus 4 Python tests and the PostgreSQL migration passed. Provider-backed storage verification, Object Lock/lifecycle attestations, Redis failure-mode testing, and Collector runtime validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 9 staged milestone: shared controls and safe disposal lifecycle view", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core now selects a Redis-backed atomic fixed-window limiter for privileged commands whenever `REDIS_URL` is configured; a no-Redis process-local limiter remains only a development fallback. A new federation-owner-authorized disposal summary exposes lifecycle state, approval count, correlation ID, timestamp, and bounded outcome category—but never object keys or versions, reasons, descriptors, raw audit/outbox records, artifacts, or model bytes. The administrator portal renders that redacted view and requires an explicit reason to record an owner approval; browser execution remains unavailable. Collector self-metrics and portable alert-rule templates were added. Full Core CI passed 39 TypeScript tests plus 4 Python tests and the portal build passed. Docker/Collector, Redis-failure, storage policy, and alert-receiver runtime validation remain deferred." },
  { date: "21 AUG 2026", title: "Phase 8 core delivered: bounded telemetry, operational throttling, and dual-authorized disposal", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The Core can now emit best-effort, allowlisted OpenTelemetry metrics to a configured local OTLP Collector while preserving a no-op default and never letting telemetry failure affect governance state. Privileged retry, dead-letter, disposal-request, approval, and execution commands are rate-limited per verified local principal and operation class before mutation, returning explicit 429/Retry-After information when blocked. A reviewed candidate can enter a storage-disposal request only after a `dispose_authorized` review; the requester cannot approve it, two distinct active federation-owner governors must approve, and an active platform administrator executes a frozen version-aware storage locator. Request, approval, execution result, correlation, and bounded failure category are immutable; candidate/release/audit lineage is retained. The full CI gate passed 39 TypeScript tests plus 4 Python tests. The portal remains review-only because no safe disposal-summary read model yet exists." },
  { date: "21 AUG 2026", title: "Phase 7 delivered: separate human administrator portal and safe governance read models", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private `hstu-research/federated-aggregator-admin-portal` repository contains a separate React/Vite human control surface for delivery operations, candidate/release lineage, and review-only retention work. The Core exposes only federation-scoped, role-authorized candidate/release summaries; it never returns artifact/model bytes, patient data, raw event payloads, approval-policy internals, or release envelopes through the portal. Retry/dead-letter controls require explicit reasoned confirmation and preserve correlation/audit evidence. The portal uses visibly labeled preview fixtures until a Core URL, explicit federation ID, and future OIDC session adapter are configured. The Core CI passed 36 TypeScript tests plus 4 Python tests, including protected PostgreSQL read-model integration coverage; the portal production build passed." },
  { date: "21 AUG 2026", title: "Phase 6 core delivered: dependency readiness and controlled outbox operations", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The control plane now distinguishes process liveness from dependency-aware readiness across PostgreSQL, Redis, and object storage. Transactional-outbox events carry explicit pending, published, or dead-lettered delivery state, safe failure metadata, and immutable operator-action evidence. Only an active platform administrator can inspect delivery summaries, request a retry, dead-letter an unpublished event, or review retention-due candidates; event payloads stay immutable and are not returned by the operations view. The publisher excludes dead-lettered events from claim, acknowledgement, and failure paths. Full CI passed 36 TypeScript tests plus 4 Python tests." },
  { date: "21 AUG 2026", title: "Phase 5 core delivered: governed candidate, evidence, release, rollback, and retention lifecycle", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "An accepted aggregation result is now only the start of a governed candidate lifecycle, not an automatic model release. The core freezes the candidate descriptor, accepted worker-result digest, protocol, release policy, and retention date; it accepts descriptor-only evaluation evidence, enforces that a creator cannot approve their own candidate, counts distinct owner-organization approvals, and publishes an immutable release envelope bound to candidate, evidence, and approval digests. Controlled rollback either selects a compatible published fallback or suspends the release with a reason. Retention decisions are recorded for review only; no object is automatically deleted. The full CI gate passed 32 TypeScript tests plus 4 Python tests." },
  { date: "21 AUG 2026", title: "Phase 4 core delivered: verified dispatch, deterministic aggregation, and safe worker reconciliation", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A sealed round can now freeze its exact verified, round-bound model-update descriptors into a versioned Node–Python command with a canonical digest. A lease-aware transactional-outbox publisher dispatches only committed jobs through a retry-safe BullMQ job identity; the isolated Python worker performs deterministic weighted FedAvg/FedProx-compatible server aggregation and returns a descriptor-only result. A separate active ML-worker identity must match the federation-owner organization, and its result must match the dispatched command, immutable input evidence, and digest before candidate-ready state is recorded. Stale, malformed, mismatched, or duplicate callbacks cannot mutate candidate state. The full CI gate passed 31 TypeScript tests plus 4 Python tests, including PostgreSQL migration and reconciliation coverage." },
  { date: "21 AUG 2026", title: "Phase 3 core delivered: descriptor-only artifact intake and quarantine", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private core now issues a short-lived, checksum-constrained S3-compatible upload intent for a generated staging key while keeping artifact bytes outside the API and PostgreSQL. Artifact, upload-intent, and append-only verification records preserve only descriptors, manifests, integrity facts, audit events, and outbox evidence. Local membership and federation participation govern creation; metadata mismatch, expiry, or an unavailable object is quarantined. The PostgreSQL migration ran successfully and the Phase 3 suite passes 24 tests." },
  { date: "21 AUG 2026", title: "Phase 2 core delivered: persistence, local authorization, and controlled API edge", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private product-core repository now has a reviewed Drizzle/PostgreSQL migration covering governance, participation, protocol/round history, audit, idempotency, and transactional outbox records. A remote-JWKS OIDC adapter validates issuer/audience/signature; a verified human still requires an active local principal and membership scope. NestJS provides liveness, dependency-aware readiness, and an authorization-filtered federation read. The migration executed on PostgreSQL 16 and the Phase 2 evidence suite passes 17 tests, including atomic state/audit/outbox commit and rollback." },
  { date: "21 AUG 2026", title: "Product-core repository established: tested local governance baseline", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private `hstu-research/federated-aggregator-core` repository holds the Phase 0–1 foundation: strict TypeScript/Python workspaces, contracts and ports, local dependency topology, CI, and deterministic domain tests for scoped memberships, non-human workload separation, protocol immutability, and round transitions. The baseline retains the approved OIDC/Clerk-ready human boundary, local authorization authority, workload credential separation, and MetaMask deferral." },
  { date: "21 AUG 2026", title: "Handoff plan fixed: local authority required; Clerk supported; MetaMask deferred", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The first core release requires local PostgreSQL records for users, organizations, memberships, workloads, federation scope, and evidence-backed authorization. Human sign-in remains provider-owned through OIDC; Clerk is an acceptable managed option for a later portal, but its session/organization context cannot replace backend policy. Hospital and worker identities remain separate short-lived credentials. MetaMask/SIWE is a future optional human authentication factor only, with no v1 schema or runtime path." },
  { date: "21 AUG 2026", title: "Engineering standard defined: modular monorepo, clean boundaries, and layered proof", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The future core repository is specified as a pnpm/TypeScript workspace plus independent Python packages: NestJS API, Node dispatch worker, and private ML worker. Domain capabilities own policy; framework/storage/queue/identity concerns are adapters; Node–Python communication is versioned schema plus golden fixtures; clean-room behavior is preserved as verified reference tests rather than imported product coupling." },
  { date: "21 AUG 2026", title: "Full core wiring specified: authority, artifacts, jobs, workers, and recovery", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The architecture now makes every integration boundary explicit: OIDC/workload identities, NestJS command authority, PostgreSQL state/audit/outbox, constrained object storage, Redis/BullMQ dispatch, a private Python/PyTorch worker, full callback reconciliation, network isolation, observability, and governed rollback. The core is intentionally a control plane, not a hospital-data repository." },
  { date: "21 AUG 2026", title: "Workflow boundary formalized: round-to-release evidence chain", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The core workflow now separates protocol activation, eligible-node selection, local training, submission quarantine, frozen-input aggregation, evaluation evidence, accountable release approval, and rollback. It records FedProx μ as client-side provenance and excludes raw hospital data from the core." },
  { date: "20 AUG 2026", title: "Technical boundary accepted for review: Node.js control, Python ML", status: "PROVISIONAL" as const, icon: GitCommitHorizontal, body: "The next architecture gate proposes a NestJS modular control plane, PostgreSQL domain state, artifact storage, and a separate PyTorch worker contract. Earlier prototypes are explicitly classified as reuse, rewrite, or defer." },
  { date: "20 AUG 2026", title: "Requirements gate opened before core architecture", status: "PROVISIONAL" as const, icon: FileWarning, body: "The product now has a written non-technical analysis covering stakeholder outcomes, business value, governance, research gaps, risks, and explicit assumptions to accept before backend design." },
  { date: "20 AUG 2026", title: "One product first: aggregation core and admin portal", status: "VALIDATED" as const, icon: Lightbulb, body: "Hospital nodes, hospital portals, and external coordination layers are separated from the first product. The immediate concern is a trustworthy model-release control plane." },
  { date: "20 AUG 2026", title: "Terminology correction: FedProx does not change the server’s basic role", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The proximal penalty is applied during local client optimization. The aggregator validates and combines declared client updates, records μ, and publishes the next compatible global model." },
  { date: "19 AUG 2026", title: "Legacy low-specificity / high-sensitivity result is retained as a diagnostic", status: "PROVISIONAL" as const, icon: FileWarning, body: "The pattern is not a thesis claim. It remains a debugging signal pending a corrected aggregation implementation, grouped data split, reproducible configuration, and independent metric recalculation." },
];

const chapterMarkers: Readonly<Record<number, { label: string; title: string; note: string }>> = {
  0: { label: "CURRENT RECORD", title: "Azure validation archive", note: "Bounded live proofs, release authority, and retained operational limits." },
  4: { label: "DEPLOYMENT RECORD", title: "Hosting and infrastructure", note: "Public-edge boundaries, private dependencies, and repeatable environment evidence." },
  12: { label: "GOVERNANCE RECORD", title: "Control-plane implementation", note: "Evidence-backed lifecycle controls, worker reconciliation, and constrained operations." },
  30: { label: "FOUNDATION RECORD", title: "Architecture decisions", note: "The research and authority assumptions that shaped the Core before runtime execution." }
};

const evidenceLanguage = {
  VALIDATED: "verified evidence",
  PROVISIONAL: "uncertainty retained",
  BLOCKED: "decision blocked"
} as const;

export default function ResearchLog() {
  return (
    <div className="doc-page research-page">
      <header className="doc-topbar"><p>12 / RESEARCH LOG</p><span className="topbar-meta"><CalendarDays size={15} />GMT+6 chronology</span></header>
      <section className="page-title"><p className="folio">12.0 / DECISIONS OVER TIME</p><h1>Keep the failed runs.<br /><i>They are evidence too.</i></h1><p>Every consequential change records its context, evidence, decision, consequence, status, and next action. The log is chronological by design.</p></section>
      <section className="log-ledger">
        {entries.map((entry, index) => {
          const Icon = entry.icon;
          const chapter = chapterMarkers[index];
          return (
            <div className="ledger-record" key={entry.title}>
              {chapter ? <div className="log-chapter"><span>{chapter.label}</span><div><h2>{chapter.title}</h2><p>{chapter.note}</p></div><small>INDEX / {String(index + 1).padStart(2, "0")}—{String(Math.min(index + 9, entries.length)).padStart(2, "0")}</small></div> : null}
              <article className={`log-entry status-${entry.status.toLowerCase()}`}>
                <div className="log-marker"><span>{String(index + 1).padStart(2, "0")}</span></div>
                <div className="log-date">{entry.date}</div>
                <div className="log-content"><div className="log-title-row"><h2>{entry.title}</h2><StatusStamp status={entry.status} /></div><p>{entry.body}</p><a href="#open-decisions">Evidence and decision record <ArrowUpRight size={15} /></a></div>
                <aside className="log-evidence"><Icon size={20} /><span>{evidenceLanguage[entry.status]}</span><strong>{entry.status}</strong><small>chronology / {String(index + 1).padStart(2, "0")}</small></aside>
              </article>
            </div>
          );
        })}
      </section>
      <section id="open-decisions" className="open-questions"><div><span>OPEN DECISION / 008</span><h2>Which normalization policy belongs in the production vision model?</h2></div><p>Before the actual vision architecture enters a federated round, document whether BatchNorm buffers are aggregated, retained locally, frozen, or replaced. The answer must be tested on that architecture, not inferred from the earlier MLP simulation.</p><StatusStamp status="BLOCKED" /></section>
    </div>
  );
}
