/**
 * Research Ledger design: chronological research entries preserve uncertainty in an editorial ledger,
 * with explicit evidence stamps rather than retrospective cleanup.
 */
import { ArrowUpRight, CalendarDays, FileWarning, GitCommitHorizontal, Lightbulb } from "lucide-react";
import { StatusStamp } from "@/components/StatusStamp";

const entries = [
  { date: "21 AUG 2026", title: "Phase 3 core delivered: descriptor-only artifact intake and quarantine", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private core now issues a short-lived, checksum-constrained S3-compatible upload intent for a generated staging key while keeping artifact bytes outside the API and PostgreSQL. Artifact, upload-intent, and append-only verification records preserve only descriptors, manifests, integrity facts, audit events, and outbox evidence. Local membership and federation participation govern creation; metadata mismatch, expiry, or an unavailable object is quarantined. The PostgreSQL migration ran successfully and the Phase 3 suite passes 24 tests." },
  { date: "21 AUG 2026", title: "Phase 2 core delivered: persistence, local authorization, and controlled API edge", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The private product-core repository now has a reviewed Drizzle/PostgreSQL migration covering governance, participation, protocol/round history, audit, idempotency, and transactional outbox records. A remote-JWKS OIDC adapter validates issuer/audience/signature; a verified human still requires an active local principal and membership scope. NestJS provides liveness, dependency-aware readiness, and an authorization-filtered federation read. The migration executed on PostgreSQL 16 and the Phase 2 evidence suite passes 17 tests, including atomic state/audit/outbox commit and rollback." },
  { date: "21 AUG 2026", title: "Product-core repository established: tested local governance baseline", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "A private `paradox-tech-bd/federated-aggregator-core` repository now holds the Phase 0–1 foundation: strict TypeScript/Python workspaces, contracts and ports, local dependency topology, CI, and deterministic domain tests for scoped memberships, non-human workload separation, protocol immutability, and round transitions. The baseline retains the approved OIDC/Clerk-ready human boundary, local authorization authority, workload credential separation, and MetaMask deferral." },
  { date: "21 AUG 2026", title: "Handoff plan fixed: local authority required; Clerk supported; MetaMask deferred", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The first core release requires local PostgreSQL records for users, organizations, memberships, workloads, federation scope, and evidence-backed authorization. Human sign-in remains provider-owned through OIDC; Clerk is an acceptable managed option for a later portal, but its session/organization context cannot replace backend policy. Hospital and worker identities remain separate short-lived credentials. MetaMask/SIWE is a future optional human authentication factor only, with no v1 schema or runtime path." },
  { date: "21 AUG 2026", title: "Engineering standard defined: modular monorepo, clean boundaries, and layered proof", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The future core repository is specified as a pnpm/TypeScript workspace plus independent Python packages: NestJS API, Node dispatch worker, and private ML worker. Domain capabilities own policy; framework/storage/queue/identity concerns are adapters; Node–Python communication is versioned schema plus golden fixtures; clean-room behavior is preserved as verified reference tests rather than imported product coupling." },
  { date: "21 AUG 2026", title: "Full core wiring specified: authority, artifacts, jobs, workers, and recovery", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The architecture now makes every integration boundary explicit: OIDC/workload identities, NestJS command authority, PostgreSQL state/audit/outbox, constrained object storage, Redis/BullMQ dispatch, a private Python/PyTorch worker, full callback reconciliation, network isolation, observability, and governed rollback. The core is intentionally a control plane, not a hospital-data repository." },
  { date: "21 AUG 2026", title: "Workflow boundary formalized: round-to-release evidence chain", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The core workflow now separates protocol activation, eligible-node selection, local training, submission quarantine, frozen-input aggregation, evaluation evidence, accountable release approval, and rollback. It records FedProx μ as client-side provenance and excludes raw hospital data from the core." },
  { date: "20 AUG 2026", title: "Technical boundary accepted for review: Node.js control, Python ML", status: "PROVISIONAL" as const, icon: GitCommitHorizontal, body: "The next architecture gate proposes a NestJS modular control plane, PostgreSQL domain state, artifact storage, and a separate PyTorch worker contract. Earlier prototypes are explicitly classified as reuse, rewrite, or defer." },
  { date: "20 AUG 2026", title: "Requirements gate opened before core architecture", status: "PROVISIONAL" as const, icon: FileWarning, body: "The product now has a written non-technical analysis covering stakeholder outcomes, business value, governance, research gaps, risks, and explicit assumptions to accept before backend design." },
  { date: "20 AUG 2026", title: "One product first: aggregation core and admin portal", status: "VALIDATED" as const, icon: Lightbulb, body: "Hospital nodes, hospital portals, and external coordination layers are separated from the first product. The immediate concern is a trustworthy model-release control plane." },
  { date: "20 AUG 2026", title: "Terminology correction: FedProx does not change the server’s basic role", status: "VALIDATED" as const, icon: GitCommitHorizontal, body: "The proximal penalty is applied during local client optimization. The aggregator validates and combines declared client updates, records μ, and publishes the next compatible global model." },
  { date: "19 AUG 2026", title: "Legacy low-specificity / high-sensitivity result is retained as a diagnostic", status: "PROVISIONAL" as const, icon: FileWarning, body: "The pattern is not a thesis claim. It remains a debugging signal pending a corrected aggregation implementation, grouped data split, reproducible configuration, and independent metric recalculation." },
];

export default function ResearchLog() {
  return (
    <div className="doc-page research-page">
      <header className="doc-topbar"><p>12 / RESEARCH LOG</p><span className="topbar-meta"><CalendarDays size={15} />GMT+6 chronology</span></header>
      <section className="page-title"><p className="folio">12.0 / DECISIONS OVER TIME</p><h1>Keep the failed runs.<br /><i>They are evidence too.</i></h1><p>Every consequential change records its context, evidence, decision, consequence, status, and next action. The log is chronological by design.</p></section>
      <section className="log-ledger">{entries.map((entry, index) => { const Icon = entry.icon; return <article className="log-entry" key={entry.title}><div className="log-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="log-date">{entry.date}</div><div className="log-content"><div className="log-title-row"><h2>{entry.title}</h2><StatusStamp status={entry.status} /></div><p>{entry.body}</p><a href="#open-decisions">Evidence and decision record <ArrowUpRight size={15} /></a></div><Icon className="log-icon" size={21} /></article>; })}</section>
      <section id="open-decisions" className="open-questions"><div><span>OPEN DECISION / 008</span><h2>Which normalization policy belongs in the production vision model?</h2></div><p>Before the actual vision architecture enters a federated round, document whether BatchNorm buffers are aggregated, retained locally, frozen, or replaced. The answer must be tested on that architecture, not inferred from the earlier MLP simulation.</p><StatusStamp status="BLOCKED" /></section>
    </div>
  );
}
